"""new fields in user model

Revision ID: 047b39902fdb
Revises: 49958e09577f
Create Date: 2021-05-07 11:31:27.790890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047b39902fdb'
down_revision = '49958e09577f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
