"""add language to posts

Revision ID: 386c9ad29632
Revises: e2e71911f2c0
Create Date: 2021-07-15 11:47:26.153904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386c9ad29632'
down_revision = 'e2e71911f2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
